api:
  prefix: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_v2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hoanghuy
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # khong tu tao hoac thay doi cac bang trong csdl(nguy hiem)
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  expiration: 259200000
  secret: hoanghuy123